name = "reknow-dda"
version = "0.1.0"
active_target = "example_win32"

[paths]
targets_dir   = "re/targets"
modules_dir   = "re/modules"
types_dir     = "re/types"
docs_dir      = "re/docs"
generated_dir = "re/generated"
