name = "reknow-dda-vc"
version = "0.1.0"
active_target = "gta_vc_1_0_win32"

[paths]
targets_dir = "targets"
modules_dir = "modules"
types_dir = "types"
docs_dir = "docs"
generated_dir = "generated"